default:

  project_name: TRISK

  project_internal:
    twodii_internal: TRUE
    project_location_ext: ~/path/to/project

  price_data_version: 2021Q1

  calculation_level: company

  company_exclusion: TRUE
