# styler: off
scenario_geography_x_ald_sector <- tibble::tribble(
                   ~scenario_geography,  ~ald_sector,                 ~scenario,
                   "AdvancedEconomies",       "Coal",             "WEO2021_APS",
                   "AdvancedEconomies",    "Oil&Gas",             "WEO2021_APS",
                   "AdvancedEconomies",      "Power",             "WEO2021_APS",
                   "AdvancedEconomies",       "Coal",             "WEO2021_SDS",
                   "AdvancedEconomies",    "Oil&Gas",             "WEO2021_SDS",
                   "AdvancedEconomies",      "Power",             "WEO2021_SDS",
                   "AdvancedEconomies",       "Coal",           "WEO2021_STEPS",
                   "AdvancedEconomies",    "Oil&Gas",           "WEO2021_STEPS",
                   "AdvancedEconomies",      "Power",           "WEO2021_STEPS",
                              "Africa",       "Coal",             "WEO2021_APS",
                              "Africa",    "Oil&Gas",             "WEO2021_APS",
                              "Africa",      "Power",             "WEO2021_APS",
                              "Africa",       "Coal",             "WEO2021_SDS",
                              "Africa",    "Oil&Gas",             "WEO2021_SDS",
                              "Africa",      "Power",             "WEO2021_SDS",
                              "Africa",       "Coal",           "WEO2021_STEPS",
                              "Africa",    "Oil&Gas",           "WEO2021_STEPS",
                              "Africa",      "Power",           "WEO2021_STEPS",
                           "Asia (R5)",       "Coal",      "NGFS2021_GCAM_B2DS",
                           "Asia (R5)",    "Oil&Gas",      "NGFS2021_GCAM_B2DS",
                           "Asia (R5)",      "Power",      "NGFS2021_GCAM_B2DS",
                           "Asia (R5)",       "Coal",        "NGFS2021_GCAM_CP",
                           "Asia (R5)",    "Oil&Gas",        "NGFS2021_GCAM_CP",
                           "Asia (R5)",      "Power",        "NGFS2021_GCAM_CP",
                           "Asia (R5)",       "Coal",       "NGFS2021_GCAM_DN0",
                           "Asia (R5)",    "Oil&Gas",       "NGFS2021_GCAM_DN0",
                           "Asia (R5)",      "Power",       "NGFS2021_GCAM_DN0",
                           "Asia (R5)",       "Coal",        "NGFS2021_GCAM_DT",
                           "Asia (R5)",    "Oil&Gas",        "NGFS2021_GCAM_DT",
                           "Asia (R5)",      "Power",        "NGFS2021_GCAM_DT",
                           "Asia (R5)",       "Coal",       "NGFS2021_GCAM_NDC",
                           "Asia (R5)",    "Oil&Gas",       "NGFS2021_GCAM_NDC",
                           "Asia (R5)",      "Power",       "NGFS2021_GCAM_NDC",
                           "Asia (R5)",       "Coal",    "NGFS2021_GCAM_NZ2050",
                           "Asia (R5)",    "Oil&Gas",    "NGFS2021_GCAM_NZ2050",
                           "Asia (R5)",      "Power",    "NGFS2021_GCAM_NZ2050",
                           "Asia (R5)",       "Coal",   "NGFS2021_MESSAGE_B2DS",
                           "Asia (R5)",    "Oil&Gas",   "NGFS2021_MESSAGE_B2DS",
                           "Asia (R5)",      "Power",   "NGFS2021_MESSAGE_B2DS",
                           "Asia (R5)",       "Coal",     "NGFS2021_MESSAGE_CP",
                           "Asia (R5)",    "Oil&Gas",     "NGFS2021_MESSAGE_CP",
                           "Asia (R5)",      "Power",     "NGFS2021_MESSAGE_CP",
                           "Asia (R5)",       "Coal",    "NGFS2021_MESSAGE_DN0",
                           "Asia (R5)",    "Oil&Gas",    "NGFS2021_MESSAGE_DN0",
                           "Asia (R5)",      "Power",    "NGFS2021_MESSAGE_DN0",
                           "Asia (R5)",       "Coal",     "NGFS2021_MESSAGE_DT",
                           "Asia (R5)",    "Oil&Gas",     "NGFS2021_MESSAGE_DT",
                           "Asia (R5)",      "Power",     "NGFS2021_MESSAGE_DT",
                           "Asia (R5)",       "Coal",    "NGFS2021_MESSAGE_NDC",
                           "Asia (R5)",    "Oil&Gas",    "NGFS2021_MESSAGE_NDC",
                           "Asia (R5)",      "Power",    "NGFS2021_MESSAGE_NDC",
                           "Asia (R5)",       "Coal", "NGFS2021_MESSAGE_NZ2050",
                           "Asia (R5)",    "Oil&Gas", "NGFS2021_MESSAGE_NZ2050",
                           "Asia (R5)",      "Power", "NGFS2021_MESSAGE_NZ2050",
                           "Asia (R5)",       "Coal",    "NGFS2021_REMIND_B2DS",
                           "Asia (R5)",    "Oil&Gas",    "NGFS2021_REMIND_B2DS",
                           "Asia (R5)",      "Power",    "NGFS2021_REMIND_B2DS",
                           "Asia (R5)",       "Coal",      "NGFS2021_REMIND_CP",
                           "Asia (R5)",    "Oil&Gas",      "NGFS2021_REMIND_CP",
                           "Asia (R5)",      "Power",      "NGFS2021_REMIND_CP",
                           "Asia (R5)",       "Coal",     "NGFS2021_REMIND_DN0",
                           "Asia (R5)",    "Oil&Gas",     "NGFS2021_REMIND_DN0",
                           "Asia (R5)",      "Power",     "NGFS2021_REMIND_DN0",
                           "Asia (R5)",       "Coal",      "NGFS2021_REMIND_DT",
                           "Asia (R5)",    "Oil&Gas",      "NGFS2021_REMIND_DT",
                           "Asia (R5)",      "Power",      "NGFS2021_REMIND_DT",
                           "Asia (R5)",       "Coal",     "NGFS2021_REMIND_NDC",
                           "Asia (R5)",    "Oil&Gas",     "NGFS2021_REMIND_NDC",
                           "Asia (R5)",      "Power",     "NGFS2021_REMIND_NDC",
                           "Asia (R5)",       "Coal",  "NGFS2021_REMIND_NZ2050",
                           "Asia (R5)",    "Oil&Gas",  "NGFS2021_REMIND_NZ2050",
                           "Asia (R5)",      "Power",  "NGFS2021_REMIND_NZ2050",
                         "AsiaPacific",       "Coal",             "WEO2021_APS",
                         "AsiaPacific",    "Oil&Gas",             "WEO2021_APS",
                         "AsiaPacific",      "Power",             "WEO2021_APS",
                         "AsiaPacific",       "Coal",             "WEO2021_SDS",
                         "AsiaPacific",    "Oil&Gas",             "WEO2021_SDS",
                         "AsiaPacific",      "Power",             "WEO2021_SDS",
                         "AsiaPacific",       "Coal",           "WEO2021_STEPS",
                         "AsiaPacific",    "Oil&Gas",           "WEO2021_STEPS",
                         "AsiaPacific",      "Power",           "WEO2021_STEPS",
                              "Brazil",      "Power",             "WEO2021_APS",
                              "Brazil",      "Power",             "WEO2021_SDS",
                              "Brazil",      "Power",           "WEO2021_STEPS",
                               "China",      "Power",             "WEO2021_APS",
                               "China",      "Power",             "WEO2021_SDS",
                               "China",      "Power",           "WEO2021_STEPS",
                                  "EU",      "Power",             "WEO2021_APS",
                                  "EU",      "Power",             "WEO2021_SDS",
                                  "EU",      "Power",           "WEO2021_STEPS",
  "Emergingmarket&developingeconomies",       "Coal",             "WEO2021_APS",
  "Emergingmarket&developingeconomies",    "Oil&Gas",             "WEO2021_APS",
  "Emergingmarket&developingeconomies",       "Coal",             "WEO2021_SDS",
  "Emergingmarket&developingeconomies",    "Oil&Gas",             "WEO2021_SDS",
  "Emergingmarket&developingeconomies",       "Coal",           "WEO2021_STEPS",
  "Emergingmarket&developingeconomies",    "Oil&Gas",           "WEO2021_STEPS",
                             "Eurasia",       "Coal",             "WEO2021_APS",
                             "Eurasia",    "Oil&Gas",             "WEO2021_APS",
                             "Eurasia",      "Power",             "WEO2021_APS",
                             "Eurasia",       "Coal",             "WEO2021_SDS",
                             "Eurasia",    "Oil&Gas",             "WEO2021_SDS",
                             "Eurasia",      "Power",             "WEO2021_SDS",
                             "Eurasia",       "Coal",           "WEO2021_STEPS",
                             "Eurasia",    "Oil&Gas",           "WEO2021_STEPS",
                             "Eurasia",      "Power",           "WEO2021_STEPS",
                              "Europe",       "Coal",             "WEO2021_APS",
                              "Europe",    "Oil&Gas",             "WEO2021_APS",
                              "Europe",      "Power",             "WEO2021_APS",
                              "Europe",       "Coal",             "WEO2021_SDS",
                              "Europe",    "Oil&Gas",             "WEO2021_SDS",
                              "Europe",      "Power",             "WEO2021_SDS",
                              "Europe",       "Coal",           "WEO2021_STEPS",
                              "Europe",    "Oil&Gas",           "WEO2021_STEPS",
                              "Europe",      "Power",           "WEO2021_STEPS",
                              "Global", "Automotive",      "GECO2021_1.5C-Unif",
                              "Global", "Automotive",         "GECO2021_CurPol",
                              "Global", "Automotive",        "GECO2021_NDC-LTS",
                              "Global",       "Coal",             "IPR2021_FPS",
                              "Global",    "Oil&Gas",             "IPR2021_FPS",
                              "Global",      "Power",             "IPR2021_FPS",
                              "Global",       "Coal",             "IPR2021_RPS",
                              "Global",    "Oil&Gas",             "IPR2021_RPS",
                              "Global",      "Power",             "IPR2021_RPS",
                              "Global",       "Coal",        "IPR2021_baseline",
                              "Global",    "Oil&Gas",        "IPR2021_baseline",
                              "Global",      "Power",        "IPR2021_baseline",
                              "Global",       "Coal",      "NGFS2021_GCAM_B2DS",
                              "Global",    "Oil&Gas",      "NGFS2021_GCAM_B2DS",
                              "Global",      "Power",      "NGFS2021_GCAM_B2DS",
                              "Global",       "Coal",        "NGFS2021_GCAM_CP",
                              "Global",    "Oil&Gas",        "NGFS2021_GCAM_CP",
                              "Global",      "Power",        "NGFS2021_GCAM_CP",
                              "Global",       "Coal",       "NGFS2021_GCAM_DN0",
                              "Global",    "Oil&Gas",       "NGFS2021_GCAM_DN0",
                              "Global",      "Power",       "NGFS2021_GCAM_DN0",
                              "Global",       "Coal",        "NGFS2021_GCAM_DT",
                              "Global",    "Oil&Gas",        "NGFS2021_GCAM_DT",
                              "Global",      "Power",        "NGFS2021_GCAM_DT",
                              "Global",       "Coal",       "NGFS2021_GCAM_NDC",
                              "Global",    "Oil&Gas",       "NGFS2021_GCAM_NDC",
                              "Global",      "Power",       "NGFS2021_GCAM_NDC",
                              "Global",       "Coal",    "NGFS2021_GCAM_NZ2050",
                              "Global",    "Oil&Gas",    "NGFS2021_GCAM_NZ2050",
                              "Global",      "Power",    "NGFS2021_GCAM_NZ2050",
                              "Global",       "Coal",   "NGFS2021_MESSAGE_B2DS",
                              "Global",    "Oil&Gas",   "NGFS2021_MESSAGE_B2DS",
                              "Global",      "Power",   "NGFS2021_MESSAGE_B2DS",
                              "Global",       "Coal",     "NGFS2021_MESSAGE_CP",
                              "Global",    "Oil&Gas",     "NGFS2021_MESSAGE_CP",
                              "Global",      "Power",     "NGFS2021_MESSAGE_CP",
                              "Global",       "Coal",    "NGFS2021_MESSAGE_DN0",
                              "Global",    "Oil&Gas",    "NGFS2021_MESSAGE_DN0",
                              "Global",      "Power",    "NGFS2021_MESSAGE_DN0",
                              "Global",       "Coal",     "NGFS2021_MESSAGE_DT",
                              "Global",    "Oil&Gas",     "NGFS2021_MESSAGE_DT",
                              "Global",      "Power",     "NGFS2021_MESSAGE_DT",
                              "Global",       "Coal",    "NGFS2021_MESSAGE_NDC",
                              "Global",    "Oil&Gas",    "NGFS2021_MESSAGE_NDC",
                              "Global",      "Power",    "NGFS2021_MESSAGE_NDC",
                              "Global",       "Coal", "NGFS2021_MESSAGE_NZ2050",
                              "Global",    "Oil&Gas", "NGFS2021_MESSAGE_NZ2050",
                              "Global",      "Power", "NGFS2021_MESSAGE_NZ2050",
                              "Global",       "Coal",    "NGFS2021_REMIND_B2DS",
                              "Global",    "Oil&Gas",    "NGFS2021_REMIND_B2DS",
                              "Global",      "Power",    "NGFS2021_REMIND_B2DS",
                              "Global",       "Coal",      "NGFS2021_REMIND_CP",
                              "Global",    "Oil&Gas",      "NGFS2021_REMIND_CP",
                              "Global",      "Power",      "NGFS2021_REMIND_CP",
                              "Global",       "Coal",     "NGFS2021_REMIND_DN0",
                              "Global",    "Oil&Gas",     "NGFS2021_REMIND_DN0",
                              "Global",      "Power",     "NGFS2021_REMIND_DN0",
                              "Global",       "Coal",      "NGFS2021_REMIND_DT",
                              "Global",    "Oil&Gas",      "NGFS2021_REMIND_DT",
                              "Global",      "Power",      "NGFS2021_REMIND_DT",
                              "Global",       "Coal",     "NGFS2021_REMIND_NDC",
                              "Global",    "Oil&Gas",     "NGFS2021_REMIND_NDC",
                              "Global",      "Power",     "NGFS2021_REMIND_NDC",
                              "Global",       "Coal",  "NGFS2021_REMIND_NZ2050",
                              "Global",    "Oil&Gas",  "NGFS2021_REMIND_NZ2050",
                              "Global",      "Power",  "NGFS2021_REMIND_NZ2050",
                              "Global",      "Power",         "Oxford2021_base",
                              "Global",       "Coal",         "Oxford2021_base",
                              "Global",    "Oil&Gas",         "Oxford2021_base",
                              "Global",      "Power",         "Oxford2021_fast",
                              "Global",       "Coal",         "Oxford2021_fast",
                              "Global",    "Oil&Gas",         "Oxford2021_fast",
                              "Global",       "Coal",             "WEO2021_APS",
                              "Global",    "Oil&Gas",             "WEO2021_APS",
                              "Global",      "Power",             "WEO2021_APS",
                              "Global", "Automotive",        "WEO2021_NZE_2050",
                              "Global",       "Coal",        "WEO2021_NZE_2050",
                              "Global",    "Oil&Gas",        "WEO2021_NZE_2050",
                              "Global",      "Power",        "WEO2021_NZE_2050",
                              "Global",       "Coal",             "WEO2021_SDS",
                              "Global",    "Oil&Gas",             "WEO2021_SDS",
                              "Global",      "Power",             "WEO2021_SDS",
                              "Global",       "Coal",           "WEO2021_STEPS",
                              "Global",    "Oil&Gas",           "WEO2021_STEPS",
                              "Global",      "Power",           "WEO2021_STEPS",
                               "India",      "Power",             "WEO2021_APS",
                               "India",      "Power",             "WEO2021_SDS",
                               "India",      "Power",           "WEO2021_STEPS",
                               "Japan",      "Power",             "WEO2021_APS",
                               "Japan",      "Power",             "WEO2021_SDS",
                               "Japan",      "Power",           "WEO2021_STEPS",
                  "Latin America (R5)",       "Coal",      "NGFS2021_GCAM_B2DS",
                  "Latin America (R5)",    "Oil&Gas",      "NGFS2021_GCAM_B2DS",
                  "Latin America (R5)",      "Power",      "NGFS2021_GCAM_B2DS",
                  "Latin America (R5)",       "Coal",        "NGFS2021_GCAM_CP",
                  "Latin America (R5)",    "Oil&Gas",        "NGFS2021_GCAM_CP",
                  "Latin America (R5)",      "Power",        "NGFS2021_GCAM_CP",
                  "Latin America (R5)",       "Coal",       "NGFS2021_GCAM_DN0",
                  "Latin America (R5)",    "Oil&Gas",       "NGFS2021_GCAM_DN0",
                  "Latin America (R5)",      "Power",       "NGFS2021_GCAM_DN0",
                  "Latin America (R5)",       "Coal",        "NGFS2021_GCAM_DT",
                  "Latin America (R5)",    "Oil&Gas",        "NGFS2021_GCAM_DT",
                  "Latin America (R5)",      "Power",        "NGFS2021_GCAM_DT",
                  "Latin America (R5)",       "Coal",       "NGFS2021_GCAM_NDC",
                  "Latin America (R5)",    "Oil&Gas",       "NGFS2021_GCAM_NDC",
                  "Latin America (R5)",      "Power",       "NGFS2021_GCAM_NDC",
                  "Latin America (R5)",       "Coal",    "NGFS2021_GCAM_NZ2050",
                  "Latin America (R5)",    "Oil&Gas",    "NGFS2021_GCAM_NZ2050",
                  "Latin America (R5)",      "Power",    "NGFS2021_GCAM_NZ2050",
                  "Latin America (R5)",       "Coal",   "NGFS2021_MESSAGE_B2DS",
                  "Latin America (R5)",    "Oil&Gas",   "NGFS2021_MESSAGE_B2DS",
                  "Latin America (R5)",      "Power",   "NGFS2021_MESSAGE_B2DS",
                  "Latin America (R5)",       "Coal",     "NGFS2021_MESSAGE_CP",
                  "Latin America (R5)",    "Oil&Gas",     "NGFS2021_MESSAGE_CP",
                  "Latin America (R5)",      "Power",     "NGFS2021_MESSAGE_CP",
                  "Latin America (R5)",       "Coal",    "NGFS2021_MESSAGE_DN0",
                  "Latin America (R5)",    "Oil&Gas",    "NGFS2021_MESSAGE_DN0",
                  "Latin America (R5)",      "Power",    "NGFS2021_MESSAGE_DN0",
                  "Latin America (R5)",       "Coal",     "NGFS2021_MESSAGE_DT",
                  "Latin America (R5)",    "Oil&Gas",     "NGFS2021_MESSAGE_DT",
                  "Latin America (R5)",      "Power",     "NGFS2021_MESSAGE_DT",
                  "Latin America (R5)",       "Coal",    "NGFS2021_MESSAGE_NDC",
                  "Latin America (R5)",    "Oil&Gas",    "NGFS2021_MESSAGE_NDC",
                  "Latin America (R5)",      "Power",    "NGFS2021_MESSAGE_NDC",
                  "Latin America (R5)",       "Coal", "NGFS2021_MESSAGE_NZ2050",
                  "Latin America (R5)",    "Oil&Gas", "NGFS2021_MESSAGE_NZ2050",
                  "Latin America (R5)",      "Power", "NGFS2021_MESSAGE_NZ2050",
                  "Latin America (R5)",       "Coal",    "NGFS2021_REMIND_B2DS",
                  "Latin America (R5)",    "Oil&Gas",    "NGFS2021_REMIND_B2DS",
                  "Latin America (R5)",      "Power",    "NGFS2021_REMIND_B2DS",
                  "Latin America (R5)",       "Coal",      "NGFS2021_REMIND_CP",
                  "Latin America (R5)",    "Oil&Gas",      "NGFS2021_REMIND_CP",
                  "Latin America (R5)",      "Power",      "NGFS2021_REMIND_CP",
                  "Latin America (R5)",       "Coal",     "NGFS2021_REMIND_DN0",
                  "Latin America (R5)",    "Oil&Gas",     "NGFS2021_REMIND_DN0",
                  "Latin America (R5)",      "Power",     "NGFS2021_REMIND_DN0",
                  "Latin America (R5)",       "Coal",      "NGFS2021_REMIND_DT",
                  "Latin America (R5)",    "Oil&Gas",      "NGFS2021_REMIND_DT",
                  "Latin America (R5)",      "Power",      "NGFS2021_REMIND_DT",
                  "Latin America (R5)",       "Coal",     "NGFS2021_REMIND_NDC",
                  "Latin America (R5)",    "Oil&Gas",     "NGFS2021_REMIND_NDC",
                  "Latin America (R5)",      "Power",     "NGFS2021_REMIND_NDC",
                  "Latin America (R5)",       "Coal",  "NGFS2021_REMIND_NZ2050",
                  "Latin America (R5)",    "Oil&Gas",  "NGFS2021_REMIND_NZ2050",
                  "Latin America (R5)",      "Power",  "NGFS2021_REMIND_NZ2050",
                        "LatinAmerica",       "Coal",             "WEO2021_APS",
                        "LatinAmerica",    "Oil&Gas",             "WEO2021_APS",
                        "LatinAmerica",       "Coal",             "WEO2021_SDS",
                        "LatinAmerica",    "Oil&Gas",             "WEO2021_SDS",
                        "LatinAmerica",       "Coal",           "WEO2021_STEPS",
                        "LatinAmerica",    "Oil&Gas",           "WEO2021_STEPS",
           "Middle East & Africa (R5)",       "Coal",      "NGFS2021_GCAM_B2DS",
           "Middle East & Africa (R5)",    "Oil&Gas",      "NGFS2021_GCAM_B2DS",
           "Middle East & Africa (R5)",      "Power",      "NGFS2021_GCAM_B2DS",
           "Middle East & Africa (R5)",       "Coal",        "NGFS2021_GCAM_CP",
           "Middle East & Africa (R5)",    "Oil&Gas",        "NGFS2021_GCAM_CP",
           "Middle East & Africa (R5)",      "Power",        "NGFS2021_GCAM_CP",
           "Middle East & Africa (R5)",       "Coal",       "NGFS2021_GCAM_DN0",
           "Middle East & Africa (R5)",    "Oil&Gas",       "NGFS2021_GCAM_DN0",
           "Middle East & Africa (R5)",      "Power",       "NGFS2021_GCAM_DN0",
           "Middle East & Africa (R5)",       "Coal",        "NGFS2021_GCAM_DT",
           "Middle East & Africa (R5)",    "Oil&Gas",        "NGFS2021_GCAM_DT",
           "Middle East & Africa (R5)",      "Power",        "NGFS2021_GCAM_DT",
           "Middle East & Africa (R5)",       "Coal",       "NGFS2021_GCAM_NDC",
           "Middle East & Africa (R5)",    "Oil&Gas",       "NGFS2021_GCAM_NDC",
           "Middle East & Africa (R5)",      "Power",       "NGFS2021_GCAM_NDC",
           "Middle East & Africa (R5)",       "Coal",    "NGFS2021_GCAM_NZ2050",
           "Middle East & Africa (R5)",    "Oil&Gas",    "NGFS2021_GCAM_NZ2050",
           "Middle East & Africa (R5)",      "Power",    "NGFS2021_GCAM_NZ2050",
           "Middle East & Africa (R5)",       "Coal",   "NGFS2021_MESSAGE_B2DS",
           "Middle East & Africa (R5)",    "Oil&Gas",   "NGFS2021_MESSAGE_B2DS",
           "Middle East & Africa (R5)",      "Power",   "NGFS2021_MESSAGE_B2DS",
           "Middle East & Africa (R5)",       "Coal",     "NGFS2021_MESSAGE_CP",
           "Middle East & Africa (R5)",    "Oil&Gas",     "NGFS2021_MESSAGE_CP",
           "Middle East & Africa (R5)",      "Power",     "NGFS2021_MESSAGE_CP",
           "Middle East & Africa (R5)",       "Coal",    "NGFS2021_MESSAGE_DN0",
           "Middle East & Africa (R5)",    "Oil&Gas",    "NGFS2021_MESSAGE_DN0",
           "Middle East & Africa (R5)",      "Power",    "NGFS2021_MESSAGE_DN0",
           "Middle East & Africa (R5)",       "Coal",     "NGFS2021_MESSAGE_DT",
           "Middle East & Africa (R5)",    "Oil&Gas",     "NGFS2021_MESSAGE_DT",
           "Middle East & Africa (R5)",      "Power",     "NGFS2021_MESSAGE_DT",
           "Middle East & Africa (R5)",       "Coal",    "NGFS2021_MESSAGE_NDC",
           "Middle East & Africa (R5)",    "Oil&Gas",    "NGFS2021_MESSAGE_NDC",
           "Middle East & Africa (R5)",      "Power",    "NGFS2021_MESSAGE_NDC",
           "Middle East & Africa (R5)",       "Coal", "NGFS2021_MESSAGE_NZ2050",
           "Middle East & Africa (R5)",    "Oil&Gas", "NGFS2021_MESSAGE_NZ2050",
           "Middle East & Africa (R5)",      "Power", "NGFS2021_MESSAGE_NZ2050",
           "Middle East & Africa (R5)",       "Coal",    "NGFS2021_REMIND_B2DS",
           "Middle East & Africa (R5)",    "Oil&Gas",    "NGFS2021_REMIND_B2DS",
           "Middle East & Africa (R5)",      "Power",    "NGFS2021_REMIND_B2DS",
           "Middle East & Africa (R5)",       "Coal",      "NGFS2021_REMIND_CP",
           "Middle East & Africa (R5)",    "Oil&Gas",      "NGFS2021_REMIND_CP",
           "Middle East & Africa (R5)",      "Power",      "NGFS2021_REMIND_CP",
           "Middle East & Africa (R5)",       "Coal",     "NGFS2021_REMIND_DN0",
           "Middle East & Africa (R5)",    "Oil&Gas",     "NGFS2021_REMIND_DN0",
           "Middle East & Africa (R5)",      "Power",     "NGFS2021_REMIND_DN0",
           "Middle East & Africa (R5)",       "Coal",      "NGFS2021_REMIND_DT",
           "Middle East & Africa (R5)",    "Oil&Gas",      "NGFS2021_REMIND_DT",
           "Middle East & Africa (R5)",      "Power",      "NGFS2021_REMIND_DT",
           "Middle East & Africa (R5)",       "Coal",     "NGFS2021_REMIND_NDC",
           "Middle East & Africa (R5)",    "Oil&Gas",     "NGFS2021_REMIND_NDC",
           "Middle East & Africa (R5)",      "Power",     "NGFS2021_REMIND_NDC",
           "Middle East & Africa (R5)",       "Coal",  "NGFS2021_REMIND_NZ2050",
           "Middle East & Africa (R5)",    "Oil&Gas",  "NGFS2021_REMIND_NZ2050",
           "Middle East & Africa (R5)",      "Power",  "NGFS2021_REMIND_NZ2050",
                          "MiddleEast",       "Coal",             "WEO2021_APS",
                          "MiddleEast",    "Oil&Gas",             "WEO2021_APS",
                          "MiddleEast",      "Power",             "WEO2021_APS",
                          "MiddleEast",       "Coal",             "WEO2021_SDS",
                          "MiddleEast",    "Oil&Gas",             "WEO2021_SDS",
                          "MiddleEast",      "Power",             "WEO2021_SDS",
                          "MiddleEast",       "Coal",           "WEO2021_STEPS",
                          "MiddleEast",    "Oil&Gas",           "WEO2021_STEPS",
                          "MiddleEast",      "Power",           "WEO2021_STEPS",
                             "NonOECD",       "Coal",             "WEO2021_APS",
                             "NonOECD",    "Oil&Gas",             "WEO2021_APS",
                             "NonOECD",      "Power",             "WEO2021_APS",
                             "NonOECD",       "Coal",             "WEO2021_SDS",
                             "NonOECD",    "Oil&Gas",             "WEO2021_SDS",
                             "NonOECD",      "Power",             "WEO2021_SDS",
                             "NonOECD",       "Coal",           "WEO2021_STEPS",
                             "NonOECD",    "Oil&Gas",           "WEO2021_STEPS",
                             "NonOECD",      "Power",           "WEO2021_STEPS",
                        "NorthAmerica",       "Coal",             "WEO2021_APS",
                        "NorthAmerica",    "Oil&Gas",             "WEO2021_APS",
                        "NorthAmerica",      "Power",             "WEO2021_APS",
                        "NorthAmerica",       "Coal",             "WEO2021_SDS",
                        "NorthAmerica",    "Oil&Gas",             "WEO2021_SDS",
                        "NorthAmerica",      "Power",             "WEO2021_SDS",
                        "NorthAmerica",       "Coal",           "WEO2021_STEPS",
                        "NorthAmerica",    "Oil&Gas",           "WEO2021_STEPS",
                        "NorthAmerica",      "Power",           "WEO2021_STEPS",
                                "OECD",       "Coal",             "WEO2021_APS",
                                "OECD",    "Oil&Gas",             "WEO2021_APS",
                                "OECD",      "Power",             "WEO2021_APS",
                                "OECD",       "Coal",             "WEO2021_SDS",
                                "OECD",    "Oil&Gas",             "WEO2021_SDS",
                                "OECD",      "Power",             "WEO2021_SDS",
                                "OECD",       "Coal",           "WEO2021_STEPS",
                                "OECD",    "Oil&Gas",           "WEO2021_STEPS",
                                "OECD",      "Power",           "WEO2021_STEPS",
                      "OECD & EU (R5)",       "Coal",      "NGFS2021_GCAM_B2DS",
                      "OECD & EU (R5)",    "Oil&Gas",      "NGFS2021_GCAM_B2DS",
                      "OECD & EU (R5)",      "Power",      "NGFS2021_GCAM_B2DS",
                      "OECD & EU (R5)",       "Coal",        "NGFS2021_GCAM_CP",
                      "OECD & EU (R5)",    "Oil&Gas",        "NGFS2021_GCAM_CP",
                      "OECD & EU (R5)",      "Power",        "NGFS2021_GCAM_CP",
                      "OECD & EU (R5)",       "Coal",       "NGFS2021_GCAM_DN0",
                      "OECD & EU (R5)",    "Oil&Gas",       "NGFS2021_GCAM_DN0",
                      "OECD & EU (R5)",      "Power",       "NGFS2021_GCAM_DN0",
                      "OECD & EU (R5)",       "Coal",        "NGFS2021_GCAM_DT",
                      "OECD & EU (R5)",    "Oil&Gas",        "NGFS2021_GCAM_DT",
                      "OECD & EU (R5)",      "Power",        "NGFS2021_GCAM_DT",
                      "OECD & EU (R5)",       "Coal",       "NGFS2021_GCAM_NDC",
                      "OECD & EU (R5)",    "Oil&Gas",       "NGFS2021_GCAM_NDC",
                      "OECD & EU (R5)",      "Power",       "NGFS2021_GCAM_NDC",
                      "OECD & EU (R5)",       "Coal",    "NGFS2021_GCAM_NZ2050",
                      "OECD & EU (R5)",    "Oil&Gas",    "NGFS2021_GCAM_NZ2050",
                      "OECD & EU (R5)",      "Power",    "NGFS2021_GCAM_NZ2050",
                      "OECD & EU (R5)",       "Coal",   "NGFS2021_MESSAGE_B2DS",
                      "OECD & EU (R5)",    "Oil&Gas",   "NGFS2021_MESSAGE_B2DS",
                      "OECD & EU (R5)",      "Power",   "NGFS2021_MESSAGE_B2DS",
                      "OECD & EU (R5)",       "Coal",     "NGFS2021_MESSAGE_CP",
                      "OECD & EU (R5)",    "Oil&Gas",     "NGFS2021_MESSAGE_CP",
                      "OECD & EU (R5)",      "Power",     "NGFS2021_MESSAGE_CP",
                      "OECD & EU (R5)",       "Coal",    "NGFS2021_MESSAGE_DN0",
                      "OECD & EU (R5)",    "Oil&Gas",    "NGFS2021_MESSAGE_DN0",
                      "OECD & EU (R5)",      "Power",    "NGFS2021_MESSAGE_DN0",
                      "OECD & EU (R5)",       "Coal",     "NGFS2021_MESSAGE_DT",
                      "OECD & EU (R5)",    "Oil&Gas",     "NGFS2021_MESSAGE_DT",
                      "OECD & EU (R5)",      "Power",     "NGFS2021_MESSAGE_DT",
                      "OECD & EU (R5)",       "Coal",    "NGFS2021_MESSAGE_NDC",
                      "OECD & EU (R5)",    "Oil&Gas",    "NGFS2021_MESSAGE_NDC",
                      "OECD & EU (R5)",      "Power",    "NGFS2021_MESSAGE_NDC",
                      "OECD & EU (R5)",       "Coal", "NGFS2021_MESSAGE_NZ2050",
                      "OECD & EU (R5)",    "Oil&Gas", "NGFS2021_MESSAGE_NZ2050",
                      "OECD & EU (R5)",      "Power", "NGFS2021_MESSAGE_NZ2050",
                      "OECD & EU (R5)",       "Coal",    "NGFS2021_REMIND_B2DS",
                      "OECD & EU (R5)",    "Oil&Gas",    "NGFS2021_REMIND_B2DS",
                      "OECD & EU (R5)",      "Power",    "NGFS2021_REMIND_B2DS",
                      "OECD & EU (R5)",       "Coal",      "NGFS2021_REMIND_CP",
                      "OECD & EU (R5)",    "Oil&Gas",      "NGFS2021_REMIND_CP",
                      "OECD & EU (R5)",      "Power",      "NGFS2021_REMIND_CP",
                      "OECD & EU (R5)",       "Coal",     "NGFS2021_REMIND_DN0",
                      "OECD & EU (R5)",    "Oil&Gas",     "NGFS2021_REMIND_DN0",
                      "OECD & EU (R5)",      "Power",     "NGFS2021_REMIND_DN0",
                      "OECD & EU (R5)",       "Coal",      "NGFS2021_REMIND_DT",
                      "OECD & EU (R5)",    "Oil&Gas",      "NGFS2021_REMIND_DT",
                      "OECD & EU (R5)",      "Power",      "NGFS2021_REMIND_DT",
                      "OECD & EU (R5)",       "Coal",     "NGFS2021_REMIND_NDC",
                      "OECD & EU (R5)",    "Oil&Gas",     "NGFS2021_REMIND_NDC",
                      "OECD & EU (R5)",      "Power",     "NGFS2021_REMIND_NDC",
                      "OECD & EU (R5)",       "Coal",  "NGFS2021_REMIND_NZ2050",
                      "OECD & EU (R5)",    "Oil&Gas",  "NGFS2021_REMIND_NZ2050",
                      "OECD & EU (R5)",      "Power",  "NGFS2021_REMIND_NZ2050",
            "Reforming Economies (R5)",       "Coal",      "NGFS2021_GCAM_B2DS",
            "Reforming Economies (R5)",    "Oil&Gas",      "NGFS2021_GCAM_B2DS",
            "Reforming Economies (R5)",      "Power",      "NGFS2021_GCAM_B2DS",
            "Reforming Economies (R5)",       "Coal",        "NGFS2021_GCAM_CP",
            "Reforming Economies (R5)",    "Oil&Gas",        "NGFS2021_GCAM_CP",
            "Reforming Economies (R5)",      "Power",        "NGFS2021_GCAM_CP",
            "Reforming Economies (R5)",       "Coal",       "NGFS2021_GCAM_DN0",
            "Reforming Economies (R5)",    "Oil&Gas",       "NGFS2021_GCAM_DN0",
            "Reforming Economies (R5)",      "Power",       "NGFS2021_GCAM_DN0",
            "Reforming Economies (R5)",       "Coal",        "NGFS2021_GCAM_DT",
            "Reforming Economies (R5)",    "Oil&Gas",        "NGFS2021_GCAM_DT",
            "Reforming Economies (R5)",      "Power",        "NGFS2021_GCAM_DT",
            "Reforming Economies (R5)",       "Coal",       "NGFS2021_GCAM_NDC",
            "Reforming Economies (R5)",    "Oil&Gas",       "NGFS2021_GCAM_NDC",
            "Reforming Economies (R5)",      "Power",       "NGFS2021_GCAM_NDC",
            "Reforming Economies (R5)",       "Coal",    "NGFS2021_GCAM_NZ2050",
            "Reforming Economies (R5)",    "Oil&Gas",    "NGFS2021_GCAM_NZ2050",
            "Reforming Economies (R5)",      "Power",    "NGFS2021_GCAM_NZ2050",
            "Reforming Economies (R5)",       "Coal",   "NGFS2021_MESSAGE_B2DS",
            "Reforming Economies (R5)",    "Oil&Gas",   "NGFS2021_MESSAGE_B2DS",
            "Reforming Economies (R5)",      "Power",   "NGFS2021_MESSAGE_B2DS",
            "Reforming Economies (R5)",       "Coal",     "NGFS2021_MESSAGE_CP",
            "Reforming Economies (R5)",    "Oil&Gas",     "NGFS2021_MESSAGE_CP",
            "Reforming Economies (R5)",      "Power",     "NGFS2021_MESSAGE_CP",
            "Reforming Economies (R5)",       "Coal",    "NGFS2021_MESSAGE_DN0",
            "Reforming Economies (R5)",    "Oil&Gas",    "NGFS2021_MESSAGE_DN0",
            "Reforming Economies (R5)",      "Power",    "NGFS2021_MESSAGE_DN0",
            "Reforming Economies (R5)",       "Coal",     "NGFS2021_MESSAGE_DT",
            "Reforming Economies (R5)",    "Oil&Gas",     "NGFS2021_MESSAGE_DT",
            "Reforming Economies (R5)",      "Power",     "NGFS2021_MESSAGE_DT",
            "Reforming Economies (R5)",       "Coal",    "NGFS2021_MESSAGE_NDC",
            "Reforming Economies (R5)",    "Oil&Gas",    "NGFS2021_MESSAGE_NDC",
            "Reforming Economies (R5)",      "Power",    "NGFS2021_MESSAGE_NDC",
            "Reforming Economies (R5)",       "Coal", "NGFS2021_MESSAGE_NZ2050",
            "Reforming Economies (R5)",    "Oil&Gas", "NGFS2021_MESSAGE_NZ2050",
            "Reforming Economies (R5)",      "Power", "NGFS2021_MESSAGE_NZ2050",
            "Reforming Economies (R5)",       "Coal",    "NGFS2021_REMIND_B2DS",
            "Reforming Economies (R5)",    "Oil&Gas",    "NGFS2021_REMIND_B2DS",
            "Reforming Economies (R5)",      "Power",    "NGFS2021_REMIND_B2DS",
            "Reforming Economies (R5)",       "Coal",      "NGFS2021_REMIND_CP",
            "Reforming Economies (R5)",    "Oil&Gas",      "NGFS2021_REMIND_CP",
            "Reforming Economies (R5)",      "Power",      "NGFS2021_REMIND_CP",
            "Reforming Economies (R5)",       "Coal",     "NGFS2021_REMIND_DN0",
            "Reforming Economies (R5)",    "Oil&Gas",     "NGFS2021_REMIND_DN0",
            "Reforming Economies (R5)",      "Power",     "NGFS2021_REMIND_DN0",
            "Reforming Economies (R5)",       "Coal",      "NGFS2021_REMIND_DT",
            "Reforming Economies (R5)",    "Oil&Gas",      "NGFS2021_REMIND_DT",
            "Reforming Economies (R5)",      "Power",      "NGFS2021_REMIND_DT",
            "Reforming Economies (R5)",       "Coal",     "NGFS2021_REMIND_NDC",
            "Reforming Economies (R5)",    "Oil&Gas",     "NGFS2021_REMIND_NDC",
            "Reforming Economies (R5)",      "Power",     "NGFS2021_REMIND_NDC",
            "Reforming Economies (R5)",       "Coal",  "NGFS2021_REMIND_NZ2050",
            "Reforming Economies (R5)",    "Oil&Gas",  "NGFS2021_REMIND_NZ2050",
            "Reforming Economies (R5)",      "Power",  "NGFS2021_REMIND_NZ2050",
                              "Russia",      "Power",             "WEO2021_APS",
                              "Russia",      "Power",             "WEO2021_SDS",
                              "Russia",      "Power",           "WEO2021_STEPS",
                                  "US",      "Power",             "WEO2021_APS",
                                  "US",      "Power",             "WEO2021_SDS",
                                  "US",      "Power",           "WEO2021_STEPS"
  )

# styler: on

usethis::use_data(scenario_geography_x_ald_sector, overwrite = TRUE)
