# styler: off
scenario_geography_x_ald_sector <- tibble::tribble(
  ~scenario_geography,  ~ald_sector,
  "AdvancedEconomies",       "Coal",
  "AdvancedEconomies",    "Oil&Gas",
  "AdvancedEconomies",      "Power",
  "Africa",      "Power",
  "Africa",       "Coal",
  "Africa",    "Oil&Gas",
  "AsiaPacific",      "Power",
  "AsiaPacific",       "Coal",
  "AsiaPacific",    "Oil&Gas",
  "Brazil",      "Power",
  "CentralandSouthAmerica",      "Power",
  "CentralandSouthAmerica",       "Coal",
  "CentralandSouthAmerica",    "Oil&Gas",
  "China",      "Power",
  "DevelopingEconomies",       "Coal",
  "DevelopingEconomies",    "Oil&Gas",
  "DevelopingEconomies",      "Power",
  "EU",      "Power",
  "EU",    "Oil&Gas",
  "Eurasia",      "Power",
  "Eurasia",       "Coal",
  "Eurasia",    "Oil&Gas",
  "Europe",      "Power",
  "Europe",       "Coal",
  "Europe",    "Oil&Gas",
  "Global", "Automotive",
  "Global",      "Power",
  "Global",       "Coal",
  "Global",    "Oil&Gas",
  "India",      "Power",
  "Japan",      "Power",
  "MiddleEast",      "Power",
  "MiddleEast",       "Coal",
  "MiddleEast",    "Oil&Gas",
  "NonOECD",      "Power",
  "NonOECD",       "Coal",
  "NonOECD",    "Oil&Gas",
  "NorthAmerica",      "Power",
  "NorthAmerica",       "Coal",
  "NorthAmerica",    "Oil&Gas",
  "OECD",      "Power",
  "OECD",       "Coal",
  "OECD",    "Oil&Gas",
  "Russia",      "Power",
  "SouthAfrica",      "Power",
  "US",      "Power"
)
# styler: on

usethis::use_data(scenario_geography_x_ald_sector, overwrite = TRUE)
