#styler: off

stress_test_arguments_numeric <- tibble::tribble(
                      ~name,       ~type,        ~default,                                                                                                                                                                                                                                                                                                                                                          ~allowed,    ~min,    ~max,
               "asset_type", "character",              NA,                                                                                                                                                                                                                                                                                                                                            "equity, bonds, loans",      NA,      NA,
                      "lgd",    "double",          "0.45",                                                                                                                                                                                                                                                                                                                                                                NA,   "0.3",   "0.9",
           "risk_free_rate",    "double",          "0.02",                                                                                                                                                                                                                                                                                                                                                                NA,     "0",  "0.05",
            "discount_rate",    "double",          "0.07",                                                                                                                                                                                                                                                                                                                                                                NA, "0.015",   "0.1",
              "growth_rate",    "double",          "0.03",                                                                                                                                                                                                                                                                                                                                                                NA,  "0.01", "0.099",
  "div_netprofit_prop_coef",    "double",             "1",                                                                                                                                                                                                                                                                                                                                                                NA,   "0.8",     "1",
               "shock_year",    "double",          "2030",                                                                                                                                                                                                                                                                                                                                                                NA,  "2025",  "2035",
               "start_year",    "double",          "2022",                                                                                                                                                                                                                                                                                                                                                                NA,  "2022",  "2022",
        "settlement_factor",    "double",             "1",                                                                                                                                                                                                                                                                                                                                                                NA,     "0",     "1",
   "exp_share_damages_paid",    "double",         "0.027",                                                                                                                                                                                                                                                                                                                                                                NA,     "0",     "1",
                      "scc",    "double",            "40",                                                                                                                                                                                                                                                                                                                                                                NA,     "0", "10000",
       "market_passthrough",    "double",             "0",                                                                                                                                                                                                                                                                                                                                                                NA,     "0",     "1",
       "financial_stimulus",    "double",             "1",                                                                                                                                                                                                                                                                                                                                                                NA,     "1",     "5",
  )


# styler: on

usethis::use_data(stress_test_arguments_numeric, overwrite = TRUE)
