#styler: off

stress_test_arguments <- tibble::tribble(
                      ~name,       ~type,        ~default,                                                                                                                                                                                                                                                                                                                                                          ~allowed,    ~min,    ~max,
               "asset_type", "character",              NA,                                                                                                                                                                                                                                                                                                                                            "equity, bonds, loans",      NA,      NA,
        "baseline_scenario", "character", "WEO2021_STEPS",                                                                                                                                                                          "WEO2021_STEPS, GECO2021_CurPol, WEO2021_APS, NGFS2021_GCAM_CP, NGFS2021_GCAM_NDC, NGFS2021_MESSAGE_CP, NGFS2021_MESSAGE_NDC, NGFS2021_REMIND_CP, NGFS2021_REMIND_NDC, IPR2021_baseline, Oxford2021_base",      NA,      NA,
           "shock_scenario", "character",   "WEO2021_SDS", "WEO2021_SDS, WEO2021_NZE_2050, GECO2021_1.5C-Unif, GECO2021_NDC-LTS, NGFS2021_GCAM_B2DS, NGFS2021_GCAM_DN0, NGFS2021_GCAM_DT, NGFS2021_GCAM_NZ2050, NGFS2021_MESSAGE_B2DS, NGFS2021_MESSAGE_DN0, NGFS2021_MESSAGE_DT, NGFS2021_MESSAGE_NZ2050, NGFS2021_REMIND_B2DS, NGFS2021_REMIND_DN0, NGFS2021_REMIND_DT, NGFS2021_REMIND_NZ2050, IPR2021_FPS, IPR2021_RPS, Oxford2021_fast",      NA,      NA,
                      "lgd",    "double",          "0.45",                                                                                                                                                                                                                                                                                                                                                                NA,   "0.3",   "0.9",
           "risk_free_rate",    "double",          "0.02",                                                                                                                                                                                                                                                                                                                                                                NA,     "0",  "0.05",
            "discount_rate",    "double",          "0.07",                                                                                                                                                                                                                                                                                                                                                                NA, "0.015",   "0.1",
              "growth_rate",    "double",          "0.03",                                                                                                                                                                                                                                                                                                                                                                NA,  "0.01", "0.099",
  "div_netprofit_prop_coef",    "double",             "1",                                                                                                                                                                                                                                                                                                                                                                NA,   "0.8",     "1",
               "shock_year",    "double",          "2030",                                                                                                                                                                                                                                                                                                                                                                NA,  "2025",  "2035",
       "scenario_geography", "character",        "Global","AdvancedEconomies, Africa, AsiaPacific, Brazil, China, EmergingMarketAndDevelopingEconomies, Eurasia, Europe, Global, India, Indonesia, Japan, LatinAmerica, MiddleEast, MiddleEastAndAfrica, Non-OECD, NorthAmerica, OECD, OecdAndEu, ReformingEconomies, Russia, UnitedStates",                                                                                      NA,      NA,
               "start_year",    "double",          "2022",                                                                                                                                                                                                                                                                                                                                                                NA,  "2022",  "2022",
        "settlement_factor",    "double",             "1",                                                                                                                                                                                                                                                                                                                                                                NA,     "0",     "1",
   "exp_share_damages_paid",    "double",         "0.027",                                                                                                                                                                                                                                                                                                                                                                NA,     "0",     "1",
                      "scc",    "double",            "40",                                                                                                                                                                                                                                                                                                                                                                NA,     "0", "10000",
       "carbon_price_model", "character", "no_carbon_tax",                                                                                                                                                                                                                                                                                                                           "no_carbon_tax, NZ2050, NDC, DN0, B2DS, B2DS_Indonesia, NZ2050_Indonesia, NDC_Indonesia, DN0_Indonesia, Current Policies, Delayed transition, NDC_Indonesia_market_assumption, NDC_Indonesia_moderate, NZ2050_Indonesia_market_assumption",      NA,      NA,
       "market_passthrough",    "double",             "0",                                                                                                                                                                                                                                                                                                                                                                NA,     "0",     "1",
       "financial_stimulus",    "double",             "1",                                                                                                                                                                                                                                                                                                                                                                NA,     "1",     "5"
  )


# styler: on

usethis::use_data(stress_test_arguments, overwrite = TRUE)
