# library(dplyr)
# library(stringr)
#
# scenario_pairs <-
#   expand.grid(
#     baseline_scenario = available_baseline_scenario,
#     shock_scenario = available_shock_scenario
#   )
# # This block removes incompatible scenario pairs
# # matching those where name match before the last "_"
# scenario_pairs <-
#   scenario_pairs |>
#   dplyr::rowwise() |>
#   dplyr::filter(paste(head(
#     stringr::str_split(baseline_scenario, "_")[[1]], -1
#   ), collapse = "_") == paste(head(
#     stringr::str_split(shock_scenario, "_")[[1]], -1
#   ), collapse = "_"))
#
# # # TODO TEMP FIX REMOVE
# scenario_pairs <- dplyr::bind_rows(
#   scenario_pairs,
#   tibble::tribble(
#     ~baseline_scenario, ~shock_scenario,
#     "WEO2021_STEPS", "WEO2021_NZE_2050"
#   )
# )
# df <- scenario_pairs%>% cross_join(tibble::tribble(~carbon_price_model , "no_carbon_tax", "NZ2050", "NDC", "DN0", "B2DS"))
#
#
# # Assuming your dataframe is named df
# df_filtered <- df %>%
#   mutate(
#     last_part_shock = str_extract(shock_scenario, "(?<=_)[^_]+$"),
#     last_part_baseline = str_extract(baseline_scenario, "(?<=_)[^_]+$")
#   ) %>%
#   filter(
#     last_part_shock == carbon_price_model |
#       last_part_baseline == carbon_price_model |
#       carbon_price_model == "no_carbon_tax"
#   ) %>%
#   select(-c(last_part_shock, last_part_baseline))
#
# stress_test_arguments_combinations <- bind_rows(
#   df_filtered %>% inner_join(Scenarios_AnalysisInput %>% distinct(scenario, scenario_geography), by=c("baseline_scenario"="scenario")),
#   df_filtered %>% inner_join(Scenarios_AnalysisInput %>% distinct(scenario, scenario_geography), by=c("shock_scenario"="scenario"))
# )

# styler: off


stress_test_arguments_combinations <- tibble::tribble(
  ~baseline_scenario,           ~shock_scenario, ~carbon_price_model,                    ~scenario_geography,
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                                "China",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                               "Global",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                                "India",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                         "UnitedStates",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                                 "Asia",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                                "China",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                               "Global",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                                "India",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                         "UnitedStates",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                                 "Asia",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                                "China",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                               "Global",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                                "India",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                         "UnitedStates",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                                "China",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                               "Global",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                                 "Asia",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                                "China",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                               "Global",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                   "ReformingEconomies",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                                 "Asia",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                                "China",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                               "Global",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                                "China",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                               "Global",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                                "India",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                            "Indonesia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                         "UnitedStates",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                                 "Asia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                                "China",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                               "Global",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                                "India",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                            "Indonesia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                         "UnitedStates",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                                 "Asia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                                "China",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                               "Global",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                                "India",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                            "Indonesia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                         "UnitedStates",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                                "China",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                               "Global",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                                "India",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                         "UnitedStates",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                                 "Asia",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                                "China",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                               "Global",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                                "India",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                         "UnitedStates",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                                 "Asia",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                                "China",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                               "Global",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                                "India",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                         "UnitedStates",
  "Oxford2021_base",         "Oxford2021_fast",     "no_carbon_tax",                               "Global",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                                "China",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                               "Global",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                                 "Asia",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                                "China",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                               "Global",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                   "ReformingEconomies",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                                 "Asia",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                                "China",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                               "Global",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                                "China",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                               "Global",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                                "India",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                            "Indonesia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                         "UnitedStates",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                                 "Asia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                                "China",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                               "Global",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                                "India",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                            "Indonesia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                         "UnitedStates",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                                 "Asia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                                "China",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                               "Global",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                                "India",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                            "Indonesia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                         "UnitedStates",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                    "AdvancedEconomies",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                               "Africa",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                          "AsiaPacific",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                               "Brazil",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                "China",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax", "EmergingMarketAndDevelopingEconomies",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                 "EU27",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                              "Eurasia",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                               "Europe",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                               "Global",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                "India",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                "Japan",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                         "LatinAmerica",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                           "MiddleEast",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                             "Non-OECD",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                         "NorthAmerica",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                 "OECD",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                               "Russia",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                        "SoutheastAsia",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                         "UnitedStates",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                    "AdvancedEconomies",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                               "Africa",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                          "AsiaPacific",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                               "Brazil",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                                "China",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax", "EmergingMarketAndDevelopingEconomies",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                                 "EU27",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                              "Eurasia",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                               "Europe",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                               "Global",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                                "India",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                                "Japan",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                         "LatinAmerica",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                           "MiddleEast",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                             "Non-OECD",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                         "NorthAmerica",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                                 "OECD",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                               "Russia",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                        "SoutheastAsia",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                         "UnitedStates",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                    "AdvancedEconomies",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                               "Africa",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                          "AsiaPacific",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                               "Brazil",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                                "China",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax", "EmergingMarketAndDevelopingEconomies",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                                 "EU27",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                              "Eurasia",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                               "Europe",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                               "Global",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                                "India",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                                "Japan",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                         "LatinAmerica",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                           "MiddleEast",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                             "Non-OECD",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                         "NorthAmerica",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                                 "OECD",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                               "Russia",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                        "SoutheastAsia",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                         "UnitedStates",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                                "China",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                               "Global",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                                "India",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",     "no_carbon_tax",                         "UnitedStates",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                                 "Asia",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                                "China",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                               "Global",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                                "India",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",            "NZ2050",                         "UnitedStates",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                                 "Asia",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                                "China",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                               "Global",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                                "India",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",  "NGFS2022_REMIND_NZ2050",               "NDC",                         "UnitedStates",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                                "China",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                               "Global",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                                 "Asia",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                                "China",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                               "Global",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",            "NZ2050",                   "ReformingEconomies",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                                 "Asia",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                                "China",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                               "Global",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC", "NGFS2022_MESSAGE_NZ2050",               "NDC",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                                "China",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                               "Global",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                                "India",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                            "Indonesia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",     "no_carbon_tax",                         "UnitedStates",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                                 "Asia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                                "China",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                               "Global",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                                "India",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                            "Indonesia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",            "NZ2050",                         "UnitedStates",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                                 "Asia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                                "China",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                               "Global",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                                "India",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                            "Indonesia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",    "NGFS2022_GCAM_NZ2050",               "NDC",                         "UnitedStates",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                                "China",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                               "Global",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                                "India",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",     "no_carbon_tax",                         "UnitedStates",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                                 "Asia",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                                "China",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                               "Global",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                                "India",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",               "NDC",                         "UnitedStates",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                                 "Asia",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                                "China",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                               "Global",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                                "India",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                         "LatinAmerica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                  "MiddleEastAndAfrica",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                            "OecdAndEu",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                   "ReformingEconomies",
  "NGFS2022_REMIND_NDC",    "NGFS2022_REMIND_B2DS",              "B2DS",                         "UnitedStates",
  "Oxford2021_base",         "Oxford2021_fast",     "no_carbon_tax",                               "Global",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                                "China",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                               "Global",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                                 "Asia",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                                "China",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                               "Global",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",               "NDC",                   "ReformingEconomies",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                                 "Asia",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                                "China",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                               "Global",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                         "LatinAmerica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                  "MiddleEastAndAfrica",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                            "OecdAndEu",
  "NGFS2022_MESSAGE_NDC",   "NGFS2022_MESSAGE_B2DS",              "B2DS",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                                 "Asia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                                "China",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                               "Global",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                                "India",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                            "Indonesia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",     "no_carbon_tax",                         "UnitedStates",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                                 "Asia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                                "China",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                               "Global",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                                "India",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                            "Indonesia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",               "NDC",                         "UnitedStates",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                                 "Asia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                                "China",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                               "Global",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                                "India",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                            "Indonesia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                         "LatinAmerica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                  "MiddleEastAndAfrica",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                            "OecdAndEu",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                   "ReformingEconomies",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                        "SoutheastAsia",
  "NGFS2022_GCAM_NDC",      "NGFS2022_GCAM_B2DS",              "B2DS",                         "UnitedStates",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                            "Australia",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                               "Brazil",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                               "Canada",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                         "CoastalChina",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                  "CSA",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                  "EEU",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                 "EURA",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                  "GBR",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                  "GCC",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                               "Global",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                "India",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                "Japan",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                           "SouthKorea",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                 "MENA",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                               "Russia",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                   "SA",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                 "SEAO",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                  "SSA",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                         "UnitedStates",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                                  "WEU",
  "IPR2021_baseline",             "IPR2021_FPS",     "no_carbon_tax",                          "SouthAfrica",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                    "AdvancedEconomies",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                               "Africa",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                          "AsiaPacific",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                               "Brazil",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                                "China",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax", "EmergingMarketAndDevelopingEconomies",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                                 "EU27",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                              "Eurasia",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                               "Europe",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                               "Global",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                                "India",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                                "Japan",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                         "LatinAmerica",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                           "MiddleEast",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                             "Non-OECD",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                         "NorthAmerica",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                                 "OECD",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                               "Russia",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                        "SoutheastAsia",
  "WEO2021_STEPS",             "WEO2021_SDS",     "no_carbon_tax",                         "UnitedStates",
  "WEO2021_STEPS",        "WEO2021_NZE_2050",     "no_carbon_tax",                               "Global"
)

# styler: on

usethis::use_data(stress_test_arguments_combinations, overwrite = TRUE)
