---
title: "01 - Set up project directories for climate transition risk stress test"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Assumptions

In order to keep this vignette concise, we assume the following has been done:

1. R and RStudio are installed.
2. All required R packages are installed, specifically
`r2dii.climate.stress.test`. Note that this may require installing additional
packages. You will be prompted to install these in case any are missing.
3. The user has successfully run at least the matching part of PACTA for Banks
to produce the relevant project-specific raw input files.
4. The user has obtained all relevant input files as described in the pdf manual.

## Project input and output data structure

The analysis builds on project-specific input files that contain information on
the loan book to be analyzed and project-agnostic input files that contain
auxiliary information required for the stress test. Detailed information about
these files can be obtained from the pdf user manual. In case you need this
document, please contact <stresstest@2degrees-investing.org>.

We recommend setting up one directory that contains project-specific input files and
a separate one that contains project-agnostic input files.

The exact names and locations of these directories can be chosen by the user,
but we recommend choosing directories, from which the software can read and to
which it is allowed to write data. It is also generally recommended to avoid
special characters and white spaces in the name.

The user will also have to determine an output data directory. We recommend setting
this up as a sub directory of the project directory.

**NOTE:** It is required to set up an output directory prior to running the
analysis. If the software cannot find the directory that the user is pointing it
to, it will fail with an error.

A recommended structure for the climate transition stress test project data 
folder would look like this:

* `example_project/`
    * `project_specific_input`
    * `project_agnostic_input`
    * `output`

The project-specific input data folder would look like this:

* `project_specific_input/`
    * `raw_loanbook.csv`
    * `matched_loan_book.csv`

The project-agnostic input data folder would look like this:

* `project_agnostic_input/`
    * `prewrangled_financial_data_stress_test.csv`
    * `price_data_long_WEO2019.csv`
    * `scenario_2020.csv`
    * `Scenario_AnalysisInput_2020.csv`
    * `prewrangled_capacity_factors_WEO_2019.csv`
    * `2021-07-15_AR2020Q4_PACTA-Data (3).xlsx`

## Next steps

After completing the setup, follow the vignettes on how to run the analysis:

* [Preparing the intermediate inputs for stress testing loans](https://2degreesinvesting.github.io/r2dii.climate.stress.test/articles/articles/02-prepare-loans-inputs.html)
* [Run transition risk stress test](https://2degreesinvesting.github.io/r2dii.climate.stress.test/articles/articles/03-run-stress-test.html)
