---
title: "04 - Understand the output files of the transition risk stress test"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Reading and understanding the output files

This vignette gives a brief overview of the files that are generated by the
climate transition risk stress test provided in `r2dii.climate.stress.test` and
proceeds to explain in depth how to read the data in each of the files.

## Overview of output files

The source code generates three result (output) files after completing the 
transition or litigation risk stress test for a given set of parameters. They principally 
contain estimates of the market risk of companies in the portfolio and of 
the credit risk of said companies in a corporate loan book. The source code 
additionally outputs a log file which holds information on the settings of the current 
transition risk stress test run.

If the user follows the recommended data folder structure the output files will
be found here:

* `example_project/`
    * `output`

The output files are:

**Log file**

* log_file_\<suffix\>.txt

**Crispy output**

* crispy_output_\<suffix\>.csv

**Company trajectories**

* company_trajectories_\<suffix\>.csv


## Content of output files

In this section, we look at each result file and what each of the variables they
contain mean. The set of input parameters, common to all result files, is 
described at the end of the following list. Special attention at the end 
is also dedicated to the slight differences in the format of results created from
a sensitivity analysis.

### log_file_\<suffix\>

This is a text file that contains information on the settings of the stress
test run that created the results files. The user can check on the:


* the paths to the input ( `input_path_project_`)
and output (`output_path`) directories.
* next, a full list of the values of the input parameters for the stress test analysis
[as described here](https://2degreesinvesting.github.io/r2dii.climate.stress.test/articles/articles/02-run-stress-test.html#understanding-the-input-arguments). 
* finally, information on the companies that were excluded from the analysis due 
to cases of unsuccessful matching of PAMS results on the company financial data.

### crispy_output_\<suffix\>

This file contains 

* `company_name`: Name of the company that was analyzed.
* `sector`: Sector of the production assets analyzed.
* `business_unit`: Name that highlights the use of the carbon budget.
* `company_name`: Name of the company that was analyzed.
* `roll_up_type`: 
* `scenario_geography`: Region for which the analysis was run. This refers to
the location of assets considered as well as the regional break down of the 
scenario targets used.
* `baseline_scenario`:  
* `shock_scenario`:  
* `ldg`:  
* `risk_free`:
* `discount_rate`: 
* `dividend_rate`:
* `growth_rate`:
* `shock_year`: 
* `net_present_value_baseline`:
* `net_present_value_shock`:
* `net_present_value_difference`:
* `term`:
* `pd_baseline`: Probability of default under the baseline scenario.
* `pd_shock`: Probability of default under the shock scenario.
* `pd_difference`:



### company_trajectories_\<suffix\>

This result file contains 

* `scenario_name`: Name that highlights the use of the carbon budget compensation
mechanism and the year of the introduction of a transition policy.
* `company_name`: Name of the company that was analyzed.
* `year `: Calendar year.  
* `scenario_geography`: Region for which the analysis was run. This refers to the
location of assets considered as well as the regional break down of the 
scenario targets used.
* `ald_sector`: Sector of the production assets analyzed.
* `technology`: The technology can be understood as a sub-sector. These must be in
line with the technologies, for which the scenarios provide production pathways.
* `production_plan_company_technology`:
* `phase_out`:
* `production_baseline_scenario`:
* `production_target_scenario`:
* `production_shock_scenario`: 
* `company_id`: Unique company number, based on an Asset Resolution classification.
* `pd`: Probability of default.
* `net_profit_margin`: 
* `debt_equity_ratio`:
* `volatility`:
* `price_baseline_scenario`:
* `price_shock_scenario`:
* `net_profits_baseline_scenario`:
* `net_profits_shock_scenario`:
* `discounted_net_profits_baseline_scenario`:
* `discounted_net_profits_shock_scenario`:
* `baseline_scenario_arg`:
* `shock_scenario_arg`: 
* `lgd_arg`: Loss given default applied in the calculation of the expected loss.
*`risk_free_rate_arg` the risk free interest rate. Input parameter to the Merton
credit risk model.
* `discount_rate_arg` the annual rate at which future cash flows are discounted
when calculating the net present value of companies in the loan book. Since 
the net present values are indirect inputs into the Merton credit risk model, 
this parameter my be relevant.
* `growth_rate_arg` the perpetual 'economic' growth rate used in the discounted 
cash flow model for the calculation of terminal value of each firm in end_year + 1.
Must be positive and strictly smaller than discount_rate.
* `div_netprofit_prop_coef_arg` coefficient that indicates what share of the net
present value should be considered to derive the equity value of a company.
* `shock_year_arg` year in which the policy is introduced, that adjusts the
production values of companies to stay in line with carbon budgets.
* `scenario_geography_arg`: 
* `start_year_arg`:

While there may be some redundancy to this information, it is there to ensure 
the results remain reproducible and straightforward for the user
to understand given magnitudes in the model results. In the standard run of the 
stress test, with a single value specified for each input parameter, this
implies that the argument columns just contain one value each 
(as opposed to sensitivity analysis where the user can set multiples values 
of input parameters).

### Sensitivity Analyses

Running a sensitivity analysis produces as many sets of results as the number 
of input parameters selected for the variable of interest.To keep the ensuing 
analysis as simple as possible, the results files are named with a suffix 
indicating the parameter that was varied in the particular run and saved in a 
new output folder. Apart from the indicative naming suffix the sensitivity 
analysis results files produced have the same format as described above but 
contain the results of multiple runs in a single file. 

The variation is observed in the argument column of the parameter that 
was iterated over. Instead of just one value, it will contain values for every 
iteration of the sensitivity analysis, be it two or more.
