---
title: "05 - Understand the output files of the transition risk stress test"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Reading and understanding the output files

This vignette gives a brief overview of the files that are generated by the
climate transition risk stress test provided in `r2dii.climate.stress.test` and
proceeds to explain in depth how to read the data in each of the files.

## Overview

The source code generates nine result (output) files after completing the transition risk
stress test for a given set of parameters. They principally contain estimates of the
market risk of companies in the portfolio and of the credit risk of said companies
in a corporate loan book. The source code additionally outputs a file with 
company-level scenario production trajectories and a log file which holds 
information on the settings of the current stress test run.

**Log file**

* log_file_\<suffix\>.txt

**Company cash flow trajectory data**

* loans_company_trajectories_\<suffix\>.csv

**Market Risk**

* loans_company_value_changes_\<suffix\>.csv
* loans_portfolio_value_changes_\<suffix\>.csv

**Credit Risk**

* loans_company_expected_loss_\<suffix\>.csv
* loans_company_pd_changes_annual_\<suffix\>.csv
* loans_company_pd_changes_overall_\<suffix\>.csv
* loans_sector_pd_changes_annual_\<suffix\>.csv
* loans_sector_pd_changes_overall_\<suffix\>.csv

## Content of output files

In this section, we look at each result file and what each of the variables they
contain mean. The set of input parameters, common to all result files, is 
described at the end of the following list. Special attention at the end 
is also dedicated to the slight differences in the format of results created from
a sensitivity analysis.

### log_file_\<suffix\>

This is a text file that contains information on the settings of the stress
test run that created the results files. The user can check on the:

* `asset_type` the type of the analysed financial asset in the portfolio/loan book. 
For the for the version of the stress test described here, this would always be `loans`.
* the paths to the input (`input_path_project_specific`, `input_path_project_agnostic`)
and output (`output_path`) directories.
* next, a full list of the values of the input parameters for the stress test analysis
[as described here](https://2degreesinvesting.github.io/r2dii.climate.stress.test/articles/articles/03-run-stress-test.html#understanding-the-input-arguments). 
* finally, information on the companies that were excluded from the analysis due 
to cases of unsuccessful matching of PACTA results on the company financial data.

### loans_company_trajectories_\<suffix\>

This file contains an in detail overview of cash flow projections on the 
company-technology level for the baseline and the shock scenarios.

* `investor_name`: Name of the investor or bank for which the analysis was run.
* `portfolio_name`: Name of the portfolio or loan book managed by the investor
or bank for which the analysis was run.
* `scenario_name`: Name that highlights the use of the Carbon budget.
* `company_name`: Name of the company that was analyzed.
* `year`: Calendar year.
* `scenario_geography`: Region for which the analysis was run. This refers to
the location of assets considered as well as the regional break down of the 
scenario targets used.
* `ald_sector`: Sector of the production assets analyzed.
* `technology`: The technology can be understood as a sub-sector. These must be
in line with the technologies, for which the scenarios provide production
pathways.
* `production_plan_company_technology`: Five year forward looking production
plans, by company, technology and year.
* `phase_out`: Logical indicator, showing if the given company phases out its
production of the indicated technology during the production forecast period.
* `production_baseline_scenario`: Production plan for the combination of company
and technology under the baseline scenario.
* `production_target_scenario`: Production plan for the combination of company
and technology under the target scenario.
* `production_shock_scenario`: Production plan for the combination of company
and technology under the shock scenario.
* `production_change_target_scenario`: Year by year required absolute changes of
production for the combination of company and technology under the target
scenario.
* `company_id`: Internal company identifier.
* `pd`: Probability of default under the baseline scenario.
* `net_profit_margin`: Net profit margin of the company.
* `debt_equity_ratio`: Debt to equity ratio of the company.
* `volatility`: Volatility of the asset price of the company.
* `price_baseline_scenario`: Market price for the given year and technology
under the baseline scenario.
* `price_shock_scenario`: Market price for the given year and technology under
the shock scenario.
* `net_profits_baseline_scenario`: Annual projected net profits of the given
combination of company and technology under the baseline scenario.
* `net_profits_shock_scenario`: Annual projected net profits of the given
combination of company and technology under the shock scenario.
* `discounted_net_profits_baseline_scenario`: Annual projected discounted net
profits of the given combination of company and technology under the baseline
scenario.
* `discounted_net_profits_shock_scenario`: Annual projected discounted net
profits of the given combination of company and technology under the shock
scenario.

### loans_company_value_changes_\<suffix\>

This result file contains relative expected value changes on the
company-technology level, based on the DCF model to calculate market risk.
It additionally contains aggregations of these relative value changes to the
exposures of the companies, technologies and sectors included in the portfolio
or loan book.

* `investor_name`: Name of the investor or bank for which the analysis was run.
(Currently this is hard coded to "Meta Investor" internally)
* `portfolio_name`: Name of the portfolio or loan book managed by the investor
or bank for which the analysis was run. (Currently this is hard coded to "Meta
Investor" internally)
* `company_name`: Name of the company that was analyzed.
* `scenario_geography`: Region for which the analysis was run. This refers to the
location of assets considered as well as the regional break down of the 
scenario targets used.
* `scenario_name`: Name that highlights the use of the Carbon budget compensation
mechanism and the year of the introduction of a transition policy.
* `year_of_shock`: Year the transition policy is first introduced.
* `duration_of_shock`: Number of years the companies have to compensate for any
previous misalignment of their production plans relative to scenario targets.
When using a Carbon budget approach, this is the period between the shock year
and the end year of the analysis.
* `ald_sector`: Sector of the production assets analyzed.
* `technology`: The technology can be understood as a sub-sector. These must be in
line with the technologies, for which the scenarios provide production pathways.
* `asset_portfolio_value`: Value of all holdings of the given asset type in the
analysed portfolio.
* `company_technology_exposure`: Exposure of the portfolio or loan book to the
company_technology level. This is approximated by multiplying the company
production technology share with the overall company exposure.
* `company_technology_percent_value_change`: Relative potential value change due
to the policy shock on the company-technology level for the portfolio or loan
book at hand. Value in percentage points, i.e. a value of -2.5 indicates a
potential loss of 2.5% points for the given combination.
* `company_technology_absolute_value_change`: Potential absolute value change of
the portfolio or loan book on the company-technology level indicated.
Calculated as `company_technology_exposure * company_technology_absolute_value_change`.
* `company_exposure`: Exposure of the portfolio or loan book to the
company indicated.
* `company_percent_value_change`: Relative potential value change due to the
policy shock on the company level for the portfolio or loan book at hand. Value
in percentage points.
* `company_absolute_value_change`: Potential absolute value change of the
portfolio or loan book on the company level indicated. Calculated as
`company_absolute_value_change = company_exposure * company_percent_value_change`.
* `technology_exposure`: Exposure of the portfolio or loan book to the
technology indicated. This is an aggregate of the technology exposure across all
companies with production in the given technology.
* `technology_percent_value_change`: Relative potential value change of the sub
sector indicated by the technology across all companies with production in the
given technology. Value in percentage points.
* `technology_absolute_value_change`: Potential absolute value change of the
portfolio or loan book on the technology level indicated. Calculated as
`technology_absolute_value_change = technology_exposure * technology_percent_value_change`.
* `sector_exposure`: Exposure of the portfolio or loan book to the sector
indicated. This is an aggregate of the sector exposure across all companies with
production in the given sector.
* `sector_percent_value_change`: Relative potential value change of the sector
indicated across all companies with production in the given sector. Value in
percentage points.
* `sector_absolute_value_change`: Potential absolute value change of the
portfolio or loan book on the sector level indicated. Calculated as
`sector_absolute_value_change = sector_exposure * sector_percent_value_change`.
* `analysed_portfolio_exposure`: Exposure of the portfolio or loan book to all
sectors in scope of the analysis. This is an aggregate of the exposure across
all companies with production in the sectors that are in scope.
* `analysed_portfolio_percent_value_change`: Relative potential value change of
portfolio or loan book across all companies with production in the in-scope
sectors. Value in percentage points.
* `analysed_portfolio_absolute_value_change`: Potential absolute value change of
the portfolio or loan book on the level of in scope sectors. Calculated as
`analysed_portfolio_absolute_value_change = analysed_portfolio_exposure * analysed_portfolio_percent_value_change`.
* `total_portfolio_exposure`: Total absolute value of the assets under
management for the given asset type.
* `total_portfolio_percent_value_change`: Relative potential value change of
portfolio or loan book across all companies relative to the total portfolio
value. Note that this does not cover potential losses for companies operating in
sectors that are out of scope. Value in percentage points.
* `total_portfolio_absolute_value_change`: Potential absolute value change of
the portfolio or loan book. Calculated as
`total_portfolio_absolute_value_chang = total_portfolio_exposure * total_portfolio_percent_value_change`.
* `exclude`: Logical indicator that shows if the given combination of company
and technology was excluded from the shock because the production forecast
indicated a phase out in production.

### loans_portfolio_value_changes_\<suffix\>

This result file contains relative expected value changes on the portfolio level,
based on the DCF model to calculate market risk. It additionally contains
aggregations on the technology, sector and total levels using exposure weighting.
The columns and rows in this file are a subset of the ones included in the 
company level output. The user can refer to the explanations above for reference.

### loans_company_expected_loss_\<suffix\>

This result file contains expected changes in the probability of default and in
expected losses. The company level pd changes are used to derive loan book level
changes in expected loss.

* `scenario_name`: Name that highlights the use of the Carbon budget.
compensation mechanism and the Year of the introduction of a transition policy.
* `scenario_geography`: Region for which the analysis was run. This refers to
the location of assets considered as well as the regional break down of the 
scenario targets used.
* `investor_name`: Name of the investor or bank for which the analysis was run.
* `portfolio_name`: Name of the portfolio or loan book managed by the investor
or bank for which the analysis was run.
* `company_name`: Name of the company that was analyzed.
* `ald_sector`: Sector of the production assets analyzed.
* `pd_baseline`: Starting point probability of default for loans to the given
company in the loan book in percentage points.
* `pd_change_shock`: Change in probability of default of the given company,
based on the Merton credit risk model and a climate transition policy shock as
indicated in `scenario_name`. In percentage points. Notice: A positive number
indicates the probability of default increases, hence the expected loss also
increases.
* `lgd`: Loss given default applied in the calculation of the expected loss.
Depending on which asset type was analyzed, this will reflect the setting of
either `lgd_senior_claims_arg` or `lgd_subordinated_claims_arg`. For corporate
loan books, this reflects senior claims.
* `exposure_at_default`: The absolute amount of exposure to a company in the
given portfolio or loan book. For loan books, this is the sum of outstanding
loans (or alternatively of the credit limit) to a company.
* `expected_loss_baseline`: The expected loss of the holdings of a company in
the analyzed portfolio or loan book based on the exposure to that company under
a baseline (commonly business as usual) scenario. This is calculated as:
`expected_loss_baseline = pd_baseline * lgd * exposure_at_default`.
* `expected_loss_shock`: The expected loss of the holdings of a company in
the analyzed portfolio or loan book based on the exposure to that company under
a shock scenario (here: a late and sudden climate transition policy). This is
calculated as:
`expected_loss_shock = (pd_baseline + pd_change_shock) * lgd * exposure_at_default`.

### loans_company_pd_changes_annual_\<suffix\>

This file contains an overview of the changes of the company-level annual 
probabilities of default relative to the baseline scenario for each year 
of the analysis after the shock year.

* `scenario_name`: Name that highlights the use of the Carbon budget.
compensation mechanism and the year of the introduction of a transition policy.
* `scenario_geography`: Region for which the analysis was run. This refers to
the location of assets considered as well as the regional break down of the 
scenario targets used.
* `investor_name`: Name of the investor or bank for which the analysis was run.
* `portfolio_name`: Name of the portfolio or loan book managed by the investor
or bank for which the analysis was run.
* `company_name`: Name of the company that was analyzed.
* `ald_sector`: Sector of the production assets analyzed.
* `year`: Calendar year.
* `pd_change_shock`: Change in probability of default of the the companies in
the portfolio or loan book. This PD change assumes a loan of one year maturity
at the point in time indicated by `year`. Specifically, it shows how the
probability of default of such a loan that is rolled over every year after the
policy shock will change over time.

### loans_sector_pd_changes_annual_\<suffix\>

This file contains an overview of the changes of annual probabilities of default 
aggregated to the sector level by company exposure weight relative to the 
baseline scenario for each year of the analysis after the shock year.

* `scenario_name`: Name that highlights the use of the Carbon budget.
compensation mechanism and the Year of the introduction of a transition policy.
* `scenario_geography`: Region for which the analysis was run. This refers to
the location of assets considered as well as the regional break down of the 
scenario targets used.
* `investor_name`: Name of the investor or bank for which the analysis was run.
* `portfolio_name`: Name of the portfolio or loan book managed by the investor
or bank for which the analysis was run.
* `ald_sector`: Sector of the production assets analyzed.
* `year`: Calendar year.
* `pd_change_shock`: Change in probability of default of the the companies in
the portfolio or loan book, aggregated to the sector level. This PD change
assumes a loan of one year maturity at the point in time indicated by `year`.
Specifically, it shows how the probability of default of such a loan that is
rolled over every year after the policy shock will change over time.

### loans_company_pd_changes_overall_\<suffix\>

This file contains an overview of the company level overall probabilities
of default change for the maturities of the underlying loans.

* `scenario_name`: Name that highlights the use of the Carbon budget.
* `scenario_geography`: Region for which the analysis was run. This refers to
the location of assets considered as well as the regional break down of the 
scenario targets used.
* `investor_name`: Name of the investor or bank for which the analysis was run.
* `portfolio_name`: Name of the portfolio or loan book managed by the investor
or bank for which the analysis was run.
* `company_name`: Name of the company that was analyzed.
* `ald_sector`: Sector of the production assets analyzed.
* `term`: Years to maturity of the loans.
* `pd_change_shock`: Change in probability of default of the the companies in
the portfolio or loan book. This PD change shows the variation of the impact on
PDs by different maturities on the sector level.

### loans_sector_pd_changes_overall_\<suffix\>

This file contains an overview on the overall probabilities
of default change for the maturities of the underlying loans.

* `scenario_name`: Name that highlights the use of the Carbon budget.
* `scenario_geography`: Region for which the analysis was run. This refers to
the location of assets considered as well as the regional break down of the 
scenario targets used.
* `investor_name`: Name of the investor or bank for which the analysis was run.
* `portfolio_name`: Name of the portfolio or loan book managed by the investor
or bank for which the analysis was run.
* `ald_sector`: Sector of the production assets analyzed.
* `term`: Years to maturity of the loans.
* `pd_change_shock`: Change in probability of default of the the companies in
the portfolio or loan book, aggregated to the sector level. This PD change shows
the variation of the impact on PDs by different maturities on the sector level.

### Model Parameter Argument Columns: common to all results files

All result files discussed below contain the values of the input parameters in the
stress testing model. The information on all model input parameters [is described here](https://2degreesinvesting.github.io/r2dii.climate.stress.test/articles/articles/03-run-stress-test.html#understanding-the-input-arguments). The result files contain
the following set of input parameters:

* `asset_type_arg` is the type of the analysed financial asset in the portfolio. 
* `lgd_senior_claims_arg` is the loss given default used in the expected loss
calculation of loans for senior claims (notably for corporate loans, so this is
a potentially important parameter in this calculation)
* `lgd_subordinated_claims_arg` is the loss given default used in the expected 
loss calculation of loans for subordinated claims (notably for corporate bonds.
Not of relevance in the loans calculation)
* `risk_free_rate_arg` the risk free interest rate. Input parameter to the Merton
credit risk model.
* `discount_rate_arg` the annual rate at which future cash flows are discounted
when calculating the net present value of companies in the loan book. Since 
the net present values are indirect inputs into the Merton credit risk model, 
this parameter my be relevant.
* `div_netprofit_prop_coef_arg` Coefficient that indicates what share of the net
present value should be considered to derive the equity value of a company.
* `shock_year_arg` year in which the policy is introduced, that adjusts the
production values of companies to stay in line with carbon budgets.
* `fallback_term_arg` indicates which maturity the loans in the loan book are
assumed to have. At this point we assume these are rolled over every year.
* `scenario_geography_arg` Indicates which geographical region(s) (concerning 
asset location) results shall be calculated for.
* `use_company_terms_arg` Logical parameter, indicating if individually provided
terms for companies as configured in company_terms.csv shall be used instead of
fallback as provided in `fallback_term`. The default is FALSE. For more details
compare [Advanced data
settings](https://2degreesinvesting.github.io/r2dii.climate.stress.test/articles/articles/04-advanced-data-settings.html).

While there may be some redundancy to this information, it is there to ensure 
the results remain reproducible and straightforward for the user
to understand given magnitudes in the model results. In the standard run of the 
stress test, with a single value specified for each input parameter, this
implies that the argument columns just contain one value each 
(as opposed to sensitivity analysis where the user can set multiples values 
of input parameters).

### Sensitivity Analyses

Running a sensitivity analysis produces as many sets of results as the number 
of input parameters selected for the variable of interest.To keep the ensuing 
analysis as simple as possible, the results files are named with a suffix 
indicating the parameter that was varied in the particular run and saved in a 
new output folder. Apart from the indicative naming suffix the sensitivity 
analysis results files produced have the same format as described above but 
contain the results of multiple runs in a single file. 

The variation is observed in the argument column of the parameter that 
was iterated over. Instead of just one value, it will contain values for every 
iteration of the sensitivity analysis, be it two or more.
