---
title: "Read and understand the output files of the stress test"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Reading and understanding the output files

This vignette gives a brief overview of the files that are generated by the
climate transition risk stress test provided in `r2dii.climate.stress.test`.

## Overview

There are five output files that the user can expect when running the stress
test for a given set of parameters.

They can loosely be grouped in files that contain estimates of the market risk
of companies in the portfolio and of the credit risk of said companies in a
corporate loan book. Depending on the use case, one or the other may contain
more relevant information.

Market Risk:

* stress_test_results_loans_port_suffix.csv
* stress_test_results_loans_comp_suffix.csv

Credit Risk:

* stress_test_results_loans_comp_el_suffix.csv
* stress_test_results_loans_sector_pd_changes_annual_suffix.csv
* stress_test_results_loans_sector_pd_changes_overall_suffix.csv




