---
title: "Set up the directories for running a climate transition risk stress test"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette describes in detail, how to set up the directories that point to
the input files and will contain the output files of running a climate
transition risk stress test for loans, using `r2dii.cliamte.stress.test`.

## Assumptions

In order to keep this vignette concise, we assume the following has been set up:

1. R and RStudio are installed
2. All required R packages are installed, this specifically includes
`r2dii.data`, `r2dii.match`, `r2dii.analysis` and `r2dii.climate.stress.test`
1. The user has obtained all relevant input files as described in the pdf manual
1. The user has successfully run at least the matching part of PACTA for banks
to produce the relevant project-specific input files
1. The user has set up objects that point to the input directories for
project-specific and project-agnostic input files.

## Project-Specific files

The user needs to create a directory that will contain all project specific files.
This directory will usually be a directory on the machine that runs the analysis.
The software will read from this directory and write to it.
The user is free to choose the name of the directory, but it ius generally
recommended to avoid special characters and white spaces in the name.

Within this project directory, the user must set up a sub directory called
`inputs`, in which the project specific input files must be placed.
This means the directory, before running the stress test, will look someting
like this:

* `example_project/`
    * `inputs/`
        * `raw_loanbook.csv`
        * `matched_loan_book.csv`

Additionally, the user must set up a separate input directory for project
agnostic files that are used for the calculation of the stress test.
These files include genreal information on climate scenarios, capacity factors,
financial data, company exclusion lists etc. For information on how to obtain
these files, consult the project pdf manual.

Again, this input folder can be named by the user, will likely be on the machine
that runs the analyis and must be structured as follows:

* `analysis_input_files/`
    * `Prewrangled_financial_data_stress_test.csv`
    * `prices_data_2021Q1.csv`
    * `scenario_2020.csv`
    * `Scenario_AnalysisInput_2020.csv`
    * `capacity_factors_WEO_2020.csv`
    * `exclude-companies.csv`
    * `2021-07-15_AR2020Q4_PACTA-Data (3).xlsx`

Once these two directories have been set up including all required files,
proceed by following the instructions in the README file **LINK** (the
environment variables must point to the directories described here).

After comlpeting the setup, follow the vignettes on how to run the analysis:

**LINK1**

**LINK2**
