#' interpolate automotive sector scenario data for a specified set of years
#' note: this function should eventually be moved to the data_prep repository
#'
#' @param data Data frame. Use the data generated by loading and basic wrangling of the scenario data
#' @param interpolation_years Numeric vector. Vector of years which ought to be replaced by the interpolation
#'
#' @return Data frame
#'
#' @export
correct_automotive_scendata <- function(data, interpolation_years = NULL) {
  stopifnot(
    all(
      c(
        "source",
        "scenario_geography",
        "scenario",
        "ald_sector",
        "units",
        "technology",
        "year",
        "direction",
        "fair_share_perc"
      ) %in% colnames(data)
    )
  )

  non_auto_sector <- data %>%
    dplyr::filter(.data$ald_sector != "Automotive")

  auto_sector <- data %>%
    dplyr::filter(.data$ald_sector == "Automotive")

  # interpolation_years <- c(2031:2034, 2036:2039)

  fsp_2025 <- auto_sector %>%
    dplyr::filter(.data$year == 2025) %>%
    dplyr::rename(fsp_2025 = .data$fair_share_perc)

  fsp_2030 <- auto_sector %>%
    dplyr::filter(.data$year == 2030) %>%
    dplyr::rename(fsp_2030 = .data$fair_share_perc)

  fsp_2035 <- auto_sector %>%
    dplyr::filter(.data$year == 2035) %>%
    dplyr::rename(fsp_2035 = .data$fair_share_perc) %>%
    dplyr::inner_join(fsp_2025 %>% dplyr::select(-c(.data$direction, .data$year)), by = c("source", "technology", "scenario_geography", "ald_sector", "units", "scenario")) %>%
    dplyr::inner_join(fsp_2030 %>% dplyr::select(-c(.data$direction, .data$year)), by = c("source", "technology", "scenario_geography", "ald_sector", "units", "scenario")) %>%
    dplyr::mutate(fsp_2035 = .data$fsp_2030 + 1.075 * (.data$fsp_2030 - .data$fsp_2025))

  fsp_2040 <- auto_sector %>%
    dplyr::filter(.data$year == 2040) %>%
    dplyr::rename(fsp_2040 = .data$fair_share_perc) %>%
    dplyr::inner_join(fsp_2035 %>% dplyr::select(-c(.data$direction, .data$year)), by = c("source", "technology", "scenario_geography", "ald_sector", "units", "scenario")) %>%
    dplyr::mutate(fsp_2040 = .data$fsp_2035 + 1.2 * (.data$fsp_2035 - .data$fsp_2030)) %>%
    dplyr::select(-c(.data$fsp_2030, .data$fsp_2025, .data$year, .data$direction))

  auto_sector_int <- auto_sector %>%
    dplyr::inner_join(fsp_2040, by = c("source", "technology", "scenario_geography", "ald_sector", "units", "scenario")) %>%
    dplyr::mutate(
      fair_share_perc = dplyr::case_when(
        .data$year == 2035 ~ .data$fsp_2035,
        .data$year == 2040 ~ .data$fsp_2040,
        TRUE ~ .data$fair_share_perc
      )
    ) %>%
    dplyr::select(-c(.data$fsp_2035, .data$fsp_2040)) %>%
    dplyr::mutate(
      fair_share_perc = dplyr::case_when(
        .data$year %in% interpolation_years ~ NA_real_,
        TRUE ~ .data$fair_share_perc
      )
    ) %>%
    dplyr::group_by(.data$scenario_geography, .data$scenario, .data$source, .data$ald_sector, .data$technology) %>%
    dplyr::arrange(.data$scenario_geography, .data$scenario, .data$source, .data$ald_sector, .data$technology, .data$year) %>%
    dplyr::mutate(ip_value = zoo::na.approx(object = .data$fair_share_perc)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(fair_share_perc = ifelse(is.na(.data$fair_share_perc), .data$ip_value, .data$fair_share_perc)) %>%
    dplyr::select(-c(.data$ip_value))

  data <- non_auto_sector %>%
    dplyr::bind_rows(auto_sector_int)

  data
}

